{% set name = "pycaret" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: d1bea16403ecf848720aec53d2bccf39374025e8ae3232321b173060489aca73

build:
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
    - numpy {{ numpy }}
    - pip
    - setuptools
    - wheel

outputs:
  - name: pycaret-core
    build:
      skip: true  # [py<38]
      script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
    requirements:
      host:
        - python
        - numpy {{ numpy }}
        - pip
        - setuptools
        - wheel
      run:
        # Base
        - ipywidgets >=7.6.5  # required by pycaret.internal.display
        - ipython >=5.5.0
        - tqdm >=4.62.0  # required by pycaret.internal.display
        # Can't numpy >=1.24 because of np.float deprecation
        # numpy pinnings to satisfy plotly-resampler https://github.com/predict-idlab/plotly-resampler/blob/c60833eb4382b3072cb591b36de737dbf769a5ea/pyproject.toml#L43-L45
        - {{ pin_compatible('numpy') }}  # [py<311]
        - numpy >=1.24                   # [py>=311]
        - pandas >=1.3.0,<2.0.0  # Can't >=2.0.0 because of sktime
        - jinja2 >=1.2  # Required by pycaret.internal.utils --> pandas.io.formats.style
        - scipy <2.0.0  # Can't >=2.0.0 due to sktime
        - joblib >=1.2.0  # joblib<1.2.0 is vulnerable to Arbitrary Code Execution (https://github.com/advisories/GHSA-6hrg-qmvc-2xh8)
        - scikit-learn >=1.0
        - pyod >=1.0.8
        - imbalanced-learn >=0.8.1
        - category_encoders >=2.4.0
        - lightgbm >=3.0.0
        - numba >=0.55.0
        - requests >=2.27.1  # Required by pycaret.datasets
        - psutil >=5.9.0
        - markupsafe >=2.0.1  # Fixes Google Colab issue
        - importlib_metadata >=4.12.0
        - nbformat >=4.2.0
        - pickle5  # [py<38]
        - cloudpickle
        - deprecation >=2.1.0
        - xxhash  # for faster hashing
        - wurlitzer  # [not win]
        # Plotting
        - matplotlib-base >=3.3.0
        - scikit-plot >=0.3.7
        - yellowbrick >=1.4
        - plotly >=5.0.0
        - kaleido-core >=0.2.1
        - schemdraw ==0.15  # 0.16 only supports Python >3.8
        - plotly-resampler >=0.8.3.1
        # Time-series
        - statsmodels >=0.12.1
        - sktime >=0.16.1,!=0.17.1,<0.17.2  # Due to this bug in 0.17.1: https://github.com/sktime/sktime/issues/4468
        - tbats >=1.1.3
        - pmdarima >=1.8.0,!=1.8.1,<3.0.0 # Matches sktime
    test:
      imports:
        - pycaret
      requires:
        - pytest >=7.0.1
        - moto >=3.0.7
        - fugue >=0.8.0
        - dask-core
        - dash
        - pip
      #commands:
        # Disable pip check because of errors:
        # pycaret 3.0.2 requires kaleido, which is not installed.
        # pycaret 3.0.2 requires xxhash, which is not installed.
        # pycaret 3.0.2 has requirement numpy<1.24,>=1.21, but you have numpy 1.24.3.
        #- pip check


about:
  home: https://github.com/pycaret/pycaret
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyCaret - An open source, low-code machine learning library in Python.
  description: PyCaret - An open source, low-code machine learning library in Python.
  doc_url: https://pycaret.readthedocs.io/en/latest/
  dev_url: https://github.com/pycaret/pycaret

extra:
  recipe-maintainers:
    - melonhead901
    - mpaulonis
